import type { Metadata } from "next";
import { Plus_Jakarta_Sans, Montserrat } from "next/font/google";
import "./globals.css";
import { NavBar } from "@/components/ui/NavBar";

const MontserratSans = Montserrat({
  subsets: ["latin"],
  variable: "--font-Montserrat",
});

const PlusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-jakarta-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Build Website With Me",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${MontserratSans.variable} antialiased`}>
        <NavBar />
        <main>{children}</main>
      </body>
    </html>
  );
}
