import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NavBar } from "@/components/ui/NavBar";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-Inter",
  weight: ["200", "800"],
});

export const metadata: Metadata = {
  title: "Build Website With Me",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased min-h-screen `}>
        <NavBar />
        <main>{children}</main>
      </body>
    </html>
  );
}
